In [2]:
import numpy as np

In [11]:
out = np.zeros((7,7))

a = np.ones((5,5))

a[2,2] = 5

out[1:-1, 1:-1] = a
print(out)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
