In [39]:
import numpy as np

In [40]:
a = np.array([1,2,3], dtype = "int16")
print(a)

[1 2 3]


In [41]:
b = np.array([[8.0,9.0,3.0],[1,2,3]])
print(b)

[[8. 9. 3.]
 [1. 2. 3.]]


In [42]:
#get deimnesion
b.ndim

2

In [43]:
#get shape
a.shape

(3,)

In [44]:
b.shape

(2, 3)

In [ ]:
#et data-type
a.dtype

dtype('int16')

In [ ]:
#get item-size
a.itemsize

8

In [48]:
b = np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]
