In [1]:
import numpy as np


In [2]:
a = np.random.rand(1,4)
print(a)

[[0.82411194 0.88169805 0.86127372 0.7293984 ]]


In [3]:
b = np.random.ranf((1,4))
print(b)

[[0.6280186  0.04809305 0.28430109 0.91238956]]


In [4]:
c = np.random.randn(2,3)
print(c)

[[-0.24152057 -0.08276947 -0.11466852]
 [-0.88981789  0.09745601 -1.18169848]]


In [5]:
d = np.random.randint(1,4,5)
print(d)

[1 1 2 3 2]
