Simple here below


In [40]:
import numpy as np

In [41]:
a = np.array([1,2,3])
b = np.array([100,100,100])
c = a+b
print(c)

[101 102 103]


Broadcasting here below

In [42]:
d = np.array(a+100)
print(d)

[101 102 103]


In [43]:
print(a+100)

[101 102 103]


In [44]:
print(a * 5)

[ 5 10 15]


Row broadcasting

In [45]:
ab = np.array([[10,11,12],
              [21,22,23]])
row = np.array([[1,1,1],
               [1,1,1]])
print(ab + row)


[[11 12 13]
 [22 23 24]]


Column Broadcasting

In [46]:
matrix = np.array([[1,1],
                   [1,1],
                   [1,1]])
matrix.shape


(3, 2)

In [47]:
column = np.array([10,10,10]).reshape(-1,1)
column.shape

(3, 1)

In [48]:
print(matrix + column)

[[11 11]
 [11 11]
 [11 11]]
