In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4], dtype=np.int32)
print(x.dtype)

int32


In [11]:
y = np.array([1,2,3])
z = np.float32(y)
print(z)
print(y.dtype)
print(y)
a = np.int_(z)
print(a.dtype)

[1. 2. 3.]
int64
[1 2 3]
int64


In [12]:
f = np.array(["a", "b", "c"])
print(f)
print(f.dtype)

['a' 'b' 'c']
<U1


In [16]:
g = np.array([1,2,3])
print(g)
print(g.dtype)
g = g.astype(float)
print(g)
print(g.dtype)

[1 2 3]
int64
[1. 2. 3.]
float64
