In [10]:
import numpy as np


In [11]:
a = np.random.rand(1,4)
print(a)

[[0.79660942 0.55655101 0.33965849 0.82721309]]


In [12]:
b = np.random.ranf((1,4))
print(b)

[[0.26796538 0.10745563 0.26928784 0.00654309]]


In [13]:
c = np.random.randn(2,3)
print(c)

[[-1.33691352 -1.0879388  -1.67648583]
 [-1.77779186  1.32546653 -1.14208888]]


In [15]:
d = np.random.randint(1,4,5)
print(d)

[2 2 1 2 2]
