In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Order of the matrix
a.shape

(2, 7)

In [5]:
#accessing 13
print(a[1,5])

13


In [6]:
#accessing a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#accessing a specific column
a[:,2]

array([ 3, 10])

In [9]:
#accessing i a modern way
a[0, 1:-1:2]

array([2, 4, 6])

In [10]:
#changing a specific element in the array
a[0,4] = 10
print(a)

[[ 1  2  3  4 10  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#changing the whole column
a[:, ]