In [16]:
import numpy as np

In [17]:
a = np.array([1,2,3])

In [18]:
a.shape

(3,)

In [19]:
b = []
for i in range(1,4):
    no = int(input("Enter: "))
    b.append(no)
print(b)
print(np.array(b))
print(type(b))
print(type(np.array(b)))

[1, 2, 3]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>


In [20]:
c = np.zeros(3)
print(c)

[0. 0. 0.]


In [21]:
d = np.ones(5)
print(d)

[1. 1. 1. 1. 1.]


In [22]:
e = np.ones((2,4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
f = np.arange(1,6)
print(f)

[1 2 3 4 5]


In [24]:
g = np.empty(2)
print(g)

[1.60221072e-306 1.66889282e-307]


In [27]:
ab = np.full((2,2), 3)
print(ab)
print()
bc = np.full_like(ab, 1)
print(bc)

[[3 3]
 [3 3]]

[[1 1]
 [1 1]]
