In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = a + 3
print(b)

[4 5 6 7]


In [4]:
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])
add = c + d
print(add)

[ 6  8 10 12]


In [6]:
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])
add = np.add(c,d)
print(add)

[ 6  8 10 12]


In [5]:
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])
mul = c * d
print(mul)

[ 5 12 21 32]
